### ISSUE TITLE
Test the backend API's

### ISSUE THREAD

**Issue by weaponsforge** [weaponsforge/todo-next#3]
Test and make sure the the backend Todo CRUD api's described on Issues works as expected.

- [x] Create the POST /todo api, [#6](https://github.com/weaponsforge/todo-next/issues/6)
- [x] Create the GET /todo api, [#7](https://github.com/weaponsforge/todo-next/issues/7)
- [x] Create the PATCH /todo api, [#8](https://github.com/weaponsforge/todo-next/issues/8)
- [x] Create the DELETE /todo api, [#9](https://github.com/weaponsforge/todo-next/issues/9)
- [x] Create the GET /todos api, [#10](https://github.com/weaponsforge/todo-next/issues/10)
