### ISSUE TITLE
Create e2e tests

### ISSUE THREAD

**Issue by weaponsforge** [weaponsforge/todo-next#74]
Create an end to end (e2e) test, testing the full web app after deploying to the **development** or **production** environment that checks:

### Home Page

- [ ] The web app's home page loads

#### 1. ToDo List Page  `/todo-next/todo/`

- [ ] The ToDo list page loads and displays at least 1 ToDo item
- [ ] Clicking an item from the ToDo list page loads and displays a ToDo item

#### 2. Create ToDo Page `/todo-next/todo/create/`

- [ ] Clicking the CREATE TODO button in the ToDo List page redirects user to the Create ToDo page
- [ ] Clicking the CLEAR button will delete contents of the input fields (title, description and content)
- [ ] Clicking the SAVE button with at least one (1) incomplete input in the three (3) required inputs (title, description and content) will not save the ToDo item, and display a `"Please check your input."` text
- [ ] Clicking the SAVE button with all three (3) required inputs will save the ToDo item, displaying a dialog confirm modal that says `"Success! Successfully saved the Todo data."`
- [ ] Clicking the OK button from the dialog confirm modal from the previous step will display the newly-created ToDo item

#### 3. View ToDo Item Page `/todo-next/todo/{id}/`

- [ ] **View Todo:** Clicking the BACK button will display the **ToDo List** page, displaying the currently loaded items
- [ ] **View Todo:** If the ToDo item is newly-created, Clicking the BACK button will display the **ToDo List** page, displaying the currently loaded items plus the newly-created ToDo item.
- [ ] **Delete Todo:** Clicking the DELETE button will display a dialog confirmation modal that says: `"Delete Todo: Do you want to delete this Todo?"`
- [ ] **Delete Todo:** Clicking the CANCEL option in the **Delete Todo** confirmation modal will make the modal disappear
- [ ] **Delete Todo:** Clicking the OK option in the **Delete Todo** confirmation modal will delete the ToDo item. It will display a dialog message`"Delete Todo: The Todo was successfully deleted"` after a successful deletion.
- [ ] **Delete Todo:** Clicking the OK button in the `"Delete Todo: The Todo was successfully deleted"` deletion message modal will take the user to the **ToDo List** page

#### 4. Edit ToDo Item Page `/todo-next/todo/edit/{id}/`

- [ ] Clicking the SAVE button with at least one (1) incomplete input in the three (3) required inputs (title, description and content) will not save the ToDo item, and display a `"Please check your input."` text
- [ ] Clicking the CLEAR button will delete contents of the input fields (title, description and content)
- [ ] Clicking the SAVE button with all three (3) required inputs will save the ToDo item, displaying a dialog confirm modal that says `"Success! Successfully saved the Todo data."`
- [ ] Clicking the OK button from the dialog confirm modal from the previous step will display the newly-created ToDo item
